import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../hooks/useAuth'
import InsightsPanel, { type InsightPayload } from '../components/InsightsPanel'
import { EmptyState } from '../components/EmptyState'
import LoadingSpinner from '../components/LoadingSpinner'
import ErrorCard from '../components/ErrorCard'

interface Season { id: number; year: number }

const ROUNDS = [1, 2, 3, 4, 5] as const

export default function InsightsPage() {
  useEffect(() => { document.title = 'Insights — SPAL' }, [])
  const { user } = useAuth()

  const [season, setSeason]   = useState<Season | null>(null)
  const [round, setRound]     = useState<number | null>(null)
  const [payload, setPayload] = useState<InsightPayload | null>(null)
  const [genAt, setGenAt]     = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [roundLoading, setRoundLoading] = useState(false)
  const [noSeason, setNoSeason] = useState(false)
  const [error, setError]       = useState(false)
  const [retryKey, setRetryKey] = useState(0)

  // Load the active season, then auto-select the latest round with insights
  useEffect(() => {
    setError(false)
    supabase
      .from('seasons')
      .select('id, year')
      .eq('status', 'active')
      .maybeSingle()
      .then(async ({ data, error: fetchError }) => {
        if (fetchError) { setError(true); setLoading(false); return }
        if (!data) { setNoSeason(true); setLoading(false); return }
        setSeason(data as Season)
        // Pick the latest round that has generated insights
        const { data: insightRows } = await supabase
          .from('round_insights')
          .select('round_number')
          .eq('season_id', (data as Season).id)
          .order('round_number', { ascending: false })
          .limit(1)
        if (insightRows && insightRows.length > 0) {
          setRound(insightRows[0].round_number as number)
        }
        setLoading(false)
      })
  }, [retryKey])

  // Load insights when round is selected
  useEffect(() => {
    if (!season || round == null) { setPayload(null); setGenAt(null); return }
    setRoundLoading(true)
    supabase
      .from('round_insights')
      .select('payload, generated_at')
      .eq('season_id', season.id)
      .eq('round_number', round)
      .maybeSingle()
      .then(({ data }) => {
        if (data) {
          setPayload(data.payload as InsightPayload)
          setGenAt(data.generated_at as string)
        } else {
          setPayload(null)
          setGenAt(null)
        }
        setRoundLoading(false)
      })
  }, [season, round])

  if (loading) return <LoadingSpinner />

  if (error) return <ErrorCard onRetry={() => setRetryKey(k => k + 1)} />

  if (noSeason) {
    return (
      <EmptyState
        icon={
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="w-10 h-10">
            <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 3v11.25A2.25 2.25 0 0 0 6 16.5h2.25M3.75 3h-1.5m1.5 0h16.5m0 0h1.5m-1.5 0v11.25A2.25 2.25 0 0 1 18 16.5h-2.25m-7.5 0h7.5m-7.5 0-1 3m8.5-3 1 3m0 0 .5 1.5m-.5-1.5h-9.5m0 0-.5 1.5" />
          </svg>
        }
        title="No active season"
        body="Insights are shown here during the current active season. Historical insights are available in the season review pages."
      />
    )
  }

  return (
    <div className="space-y-8">

      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-spal-yellow">Insights</h1>
          <p className="text-spal-muted text-sm mt-0.5">
            {season?.year} season · Round-by-round statistics and highlights
          </p>
        </div>
        {user && (
          <Link to="/admin/scores" className="text-xs text-spal-muted hover:text-spal-text transition-colors">
            Admin: generate insights →
          </Link>
        )}
      </div>

      {/* Round selector */}
      <div className="flex items-center gap-2">
        <span className="text-sm text-spal-muted">Round</span>
        {ROUNDS.map(r => (
          <button
            key={r}
            onClick={() => setRound(r)}
            className={roundBtnClass(round === r)}
          >
            R{r}
          </button>
        ))}
      </div>

      {/* Content */}
      {round == null ? (
        <p className="text-spal-muted text-sm">Select a round to view insights.</p>
      ) : roundLoading ? (
        <p className="text-spal-muted text-sm">Loading…</p>
      ) : !payload ? (
        <div className="bg-spal-surface border border-white/5 rounded-lg p-8 text-center">
          <p className="text-spal-muted text-sm">
            No insights generated for Round {round} yet.
          </p>
          <p className="text-xs text-spal-muted mt-1">
            Insights are generated by the admin after round scores are finalised.
          </p>
        </div>
      ) : (
        <>
          {genAt && (
            <p className="text-xs text-spal-muted">
              Generated {new Date(genAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
            </p>
          )}
          <InsightsPanel payload={payload} />
        </>
      )}

    </div>
  )
}

function roundBtnClass(active: boolean) {
  return `px-2.5 py-1 rounded text-xs font-medium transition-colors border ${
    active
      ? 'border-spal-cerulean bg-spal-cerulean/10 text-spal-cerulean'
      : 'border-white/10 text-spal-muted hover:border-white/30 hover:text-spal-text'
  }`
}
