-- Migration 020: round_insights table
-- Stores per-round insight snapshots generated by the generate-insights Edge Function.
-- Insights are computed once from finalised scoring data and stored as a JSON payload
-- to avoid expensive multi-join queries on every page load.

CREATE TABLE public.round_insights (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  season_id    bigint NOT NULL REFERENCES public.seasons(id),
  round_number int    NOT NULL,
  payload      jsonb  NOT NULL,
  generated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (season_id, round_number)
);

ALTER TABLE public.round_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "round_insights_public_read"
  ON public.round_insights
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "round_insights_admin_write"
  ON public.round_insights
  FOR ALL TO authenticated
  USING (is_admin())
  WITH CHECK (is_admin());
